let shopItemsData = [
  {
    id: "jfhgbvnscs",
    name: "Pizza barbeque",
    price: 69000, 
    img: "./barbeque.webp",
  },
  {
    id: "ioytrhndcv",
    name: "Pizza Cheezy",
    price: 54000,
    img: "./chezzy.webp",
  },
  {
    id: "wuefbncxbsn",
    name: "Pizza Chicken",
    price: 64000,
    img: "./chicken.webp",
  },
  {
    id: "thyfhcbcv",
    name: "Pizza Chapspecial",
    price: 99000,
    img: "./choparspecial.webp",
  },
  {
    id: "thiecbawdjksadjk",
    name: "Pizza combo",
    price: 69000,
    img: "./combo.webp",
  },
  {
    id: "iuertrywebncdjksadjk",
    name: "Pizza Double Peperoni",
    price: 66000,
    img: "./doublepeperoni.webp",
  },
  {
    id: "thierytbvcbvzdhadjk",
    name: "Pizza Havayan",
    price: 64000,
    img: "./havayan.webp",
  },
  {
    id: "trfoiwfcnbcawdjksadjk",
    name: "Pizza Holiday",
    price: 86000,
    img: "./holiday.webp",
  },
  {
    id: "cbvxbcvsceldk",
    name: "Pizza Julyen",
    price: 64000,
    img: "./julyen.webp",
  },
  {
    id: "oefeferfiopijmjkhuihb",
    name: "Pizza khan",
    price: 84000,
    img: "./khan.webp",
  },
  {
    id: "febrythoiopijewyiohbjhib",
    name: "Pizza Lazzat",
    price: 66000,
    img: "./lazzet.webp",
  },
  {
    id: "tyntntrhrtytytuyuytyytbvncv",
    name: "Pizza Majnun",
    price: 65000,
    img: "./majnun.webp",
  },
  {
    id: "lilikrtytytuyuytyytbvncv",
    name: "Pizza Margarita",
    price: 57000,
    img: "./margarita.webp",
  },
  {
    id: "rtytytuyuytyytplokobvncv",
    name: "Pizza Meat",
    price: 76000,
    img: "./meat.webp",
  },
  {
    id: "rtnofgefkfmerlkvmytytuyuytyytbvncv",
    name: "Pizza Mushroom",
    price: 64000,
    img: "./mushroom.webp",
  },
  {
    id: "nvorvnvrtytytuyuytyytbvncv",
    name: "Pizza peperoni",
    price: 64000,
    img: "./peperoni.webp",
  },
  {
    id: "rrmgoitrgmuytyytbvncv",
    name: "Pizza rostbeaf",
    price: 72000,
    img: "./rostbif.webp",
  },
];